# Name of the package
name: archival-text-kit

# Import the other files
import:

# -- by EAD tag ------------------------------

  - accessrestrict.yml
  - accruals.yml
  - acqinfo
  - altformavail.yml
  - arrangement.yml
  - bibliography.yml
  - editionstmt.yml
  - langmaterial.yml
  - odd.yml
  - originalsloc.yml
  - prefercite.yml
  - processinfo.yml
  - separatedmaterial.yml
  - unittitle.yml
  - userestrict.yml

# -- General Dates Markup & Codes --------------

  - dates.yml
  - markup.yml
  - universal-aspace-codes.yml

# -- Local names & codes ------------------------

  - local-aspace-codes.yml
  - local-names.yml

# ---- Variables --------------------------------
  - variables.yml

# ---- Updater Scripts  -------------------------
  - update-text-kit-mac.sh
  - update-text-kit-mac.bat
